import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  await prisma.productDetails.createMany({
    data: [
      {
        name: "Parachute Coconut Oil 600 ml - Bottle 100 % Pure Coconut Oil",
        description: "100% Pure Coconut Oil",
        price: 50.0,
        image: ["/images/grocery/product_1.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Bajaj Almond Drop Hair Oil 500 Ml",
        description: "Almond Drop Hair Oil",
        price: 85.0,
        image: ["/images/grocery/product_2.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Pepsodent Germicheck Toothpaste 150 g",
        description: "Germicheck Toothpaste",
        price: 60.0,
        image: ["/images/grocery/product_3.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Whisper Ultra Clean Sanitary Pads For Women",
        description: "Ultra Clean Sanitary Pads",
        price: 100.0,
        image: ["/images/grocery/product_4.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Fortune Premium Kachi Ghani Pure Mustard Oil",
        description: "Premium Kachi Ghani Pure Mustard Oil",
        price: 85.0,
        image: ["/images/grocery/product_5.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Fortune Sunlite Refined Sunflower Oil",
        description: "Sunlite Refined Sunflower Oil",
        price: 85.0,
        image: ["/images/grocery/product_6.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Amul Butter",
        description: "Amul Butter",
        price: 85.0,
        image: ["/images/grocery/product_7.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Horlicks Health & Nutrition Drink Chocolate",
        description: "Health & Nutrition Drink Chocolate",
        price: 85.0,
        image: ["/images/grocery/product_8.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Brooke Bond Red Label Tea",
        description: "Red Label Tea",
        price: 85.0,
        image: ["/images/grocery/product_9.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Kellogg’s Corn Flakes Original",
        description: "Corn Flakes Original",
        price: 85.0,
        image: ["/images/grocery/product_10.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Saffola Masala Oats, Classic Masala",
        description: "Masala Oats, Classic Masala",
        price: 85.0,
        image: ["/images/grocery/product_11.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Harpic Disinfectant Toilet Cleaner Liquid",
        description: "Disinfectant Toilet Cleaner Liquid",
        price: 85.0,
        image: ["/images/grocery/product_12.jpg"],
        stock: 100,
        category: ["grocery"],
      },
      {
        name: "Fresh Strawberry, 200g",
        description: "Fresh Strawberry, 200g",
        price: 85.0,
        image: ["/images/fresh/product_13.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresho Tomato - Local 1 kg",
        description: "Fresho Tomato - Local 1 kg",
        price: 85.0,
        image: ["/images/fresh/product_14.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Lemon 5 Pcs",
        description: "Fresh Lemon 5 Pcs",
        price: 85.0,
        image: ["/images/fresh/product_15.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Blueberry",
        description: "Fresh Blueberry",
        price: 85.0,
        image: ["/images/fresh/product_16.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Cucumber, 500g",
        description: "Fresh Cucumber, 500g",
        price: 85.0,
        image: ["/images/fresh/product_17.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Organic Bell Peppers",
        description: "Fresh Organic Bell Peppers",
        price: 85.0,
        image: ["/images/fresh/product_18.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Banana Yelakki, 500 g",
        description: "Fresh Banana Yelakki, 500 g",
        price: 85.0,
        image: ["/images/fresh/product_19.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Sapota - 1 kg",
        description: "Fresh Sapota - 1 kg",
        price: 85.0,
        image: ["/images/fresh/product_20.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresho Orange - Nagpur, Regular, 1 kg",
        description: "Fresho Orange - Nagpur, Regular, 1 kg",
        price: 85.0,
        image: ["/images/fresh/product_21.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Spinach, 250g",
        description: "Fresh Spinach, 250g",
        price: 85.0,
        image: ["/images/fresh/product_22.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Pomegranate (Anar), 4 Pieces",
        description: "Fresh Pomegranate (Anar), 4 Pieces",
        price: 85.0,
        image: ["/images/fresh/product_23.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "fresho! Avocado - Organically Grown, 1 kg",
        description: "fresho! Avocado - Organically Grown, 1 kg",
        price: 85.0,
        image: ["/images/fresh/product_24.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Fresh Onion, 1kg",
        description: "Fresh Onion, 1kg",
        price: 85.0,
        image: ["/images/fresh/product_25.jpg"],
        stock: 100,
        category: ["fresh"],
      },
      {
        name: "Sprite 750 ml Colddrink",
        description: "Sprite 750 ml Colddrink",
        price: 85.0,
        image: ["/images/drinks/product_26.jpg"],
        stock: 100,
        category: ["drinks"],
      },
      {
        name: "Maaza Mango Drink",
        description: "Maaza Mango Drink",
        price: 85.0,
        image: ["/images/drinks/product_27.jpg"],
        stock: 100,
        category: ["drinks"],
      },
      {
        name: "Paper Boat Swing Mixed Fruit Medley Juice",
        description: "Paper Boat Swing Mixed Fruit Medley Juice",
        price: 85.0,
        image: ["/images/drinks/product_28.jpg"],
        stock: 100,
        category: ["drinks"],
      },
      {
        name: "Frooti Mango Drink",
        description: "Frooti Mango Drink",
        price: 85.0,
        image: ["/images/drinks/product_29.jpg"],
        stock: 100,
        category: ["drinks"],
      },
      {
        name: "Thums Up Soft Drink",
        description: "Thums Up Soft Drink",
        price: 85.0,
        image: ["/images/drinks/product_30.jpg"],
        stock: 100,
        category: ["drinks"],
      },
      {
        name: "Amul Taaza Homogenised Toned Milk 1 L Carton",
        description: "Amul Taaza Homogenised Toned Milk 1 L Carton",
        price: 85.0,
        image: ["/images/milk/product_31.jpg"],
        stock: 100,
        category: ["milk"],
      },
      {
        name: "Mother Dairy Standardised Milk 500ml",
        description: "Mother Dairy Standardised Milk 500ml",
        price: 85.0,
        image: ["/images/milk/product_32.jpeg"],
        stock: 100,
        category: ["milk"],
      },
      {
        name: "Mother Dairy Full Cream Milk 500ml",
        description: "Mother Dairy Full Cream Milk 500ml",
        price: 85.0,
        image: ["/images/milk/product_33.jpeg"],
        stock: 100,
        category: ["milk"],
      },
      {
        name: "Mother Dairy Toned Milk 500ml",
        description: "Mother Dairy Toned Milk 500ml",
        price: 85.0,
        image: ["/images/milk/product_34.webp"],
        stock: 100,
        category: ["milk"],
      },
      {
        name: "Mother Dairy Double Toned Milk 500ml",
        description: "Mother Dairy Double Toned Milk 500ml",
        price: 85.0,
        image: ["/images/milk/product_35.jpg"],
        stock: 100,
        category: ["milk"],
      },
      {
        name: "Mother Dairy Skimmed Milk 500ml",
        description: "Mother Dairy Skimmed Milk 500ml",
        price: 85.0,
        image: ["/images/milk/product_36.png"],
        stock: 100,
        category: ["milk"],
      },
    ],
  });
  console.log('Data added successfully');
}

main()
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
